# Generated by Django 5.2.7 on 2025-10-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_post_options_post_thumbnail_post_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
