# Generated by Django 5.2.7 on 2025-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog_thumbnails/1.webp', upload_to='thumbnail/%Y/%m/%d/'),
        ),
    ]
