# Generated by Django 5.2.7 on 2025-10-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, default='', max_length=25, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=25, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read Status')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='mainApp_con_sent_at_dd631d_idx'), models.Index(fields=['is_read'], name='mainApp_con_is_read_38237f_idx')],
            },
        ),
    ]
